---
- hosts: workstation

  tasks:
    - name: install Evernote
      mac_pkg: pkg_type=app
               url=http://evernote.com/download/get.php?file=EvernoteMac
               archive_type=dmg archive_path=Evernote.app
      sudo: yes

